ProjectDto:
  description: Representation of the team in the system
  type: object
  properties:
    uuid:
      type: string
    name:
      type: string
    description:
      type: string
    team:
      $ref: './team.yaml#/TeamDto'
    startDate:
      type: string
      format: date
    endDate:
      type: string
      format: date